export const categoryList = [
  "Action and Adventure",
  "Classics",
  "Comic Book or Graphic Novel",
  "Detective and Mystery",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Literary Fiction",
  "Romance",
  "Science Fiction",
  "Short Stories",
  "Suspense and Thrillers",
  "Women's Fiction",
  "Biographies and Autobiographies",
  "Cookbooks",
  "Essays",
  "History",
  "Memoir",
  "Poetry",
  "Self-Help",
  "True Crime",
];

export const genreList = [
  "Business",
  "Fantasy",
  "Children's",
  "Literary Fiction",
  "Science Fiction",
  "Thrillers",
  "Middle Grade",
  "Picture Book",
  "Romance",
  "Historical",
  "Memoir",
  "Self-Help",
  "Narrative",
  "Religion",
  "Cultural",
  "Biography",
  "History",
  "Non-Fiction",
  "Politics",
];
