export const categoryList = [
  "Action and Adventure",
  "Classics",
  "Comic Book or Graphic Novel",
  "Detective and Mystery",
  "Fantasy",
  "Historical Fiction",
  "Horror",
  "Literary Fiction",
  "Romance",
  "Science Fiction",
  "Short Stories",
  "Suspense and Thrillers",
  "Women's Fiction",
  "Biographies and Autobiographies",
  "Cookbooks",
  "Essays",
  "History",
  "Memoir",
  "Poetry",
  "Self-Help",
  "True Crime",
].sort();

export const genreList = [
  "Computer Science",
  "Business",
  "Fantasy",
  "Fiction",
  "Literary Fiction",
  "Science Fiction",
  "Thrillers",
  "Love Story",
  "Romance",
  "Historical",
  "Self-Help",
  "Narrative",
  "Religion",
  "Biography",
  "History",
  "Politics",
].sort();
